MORE-Platform/more-studymanager-frontend

src/components/shared/RelativeScheduler.vue
src/i18n/de.json
src/i18n/en.json

The Bug where (in the relative scheduler) the end date can be set before the start date has been fixed. The error messages in RelativeScheduler.Vue have also been fixed

Tt 161 relative end before start bug

---

README.md

Added instructions for selecting backend.

Documentation for backend

---

src/stores/studyStore.ts

This PR enhances the error-message handling by providing more details in the error-message to the user.
Relates to https://github.com/MORE-Platform/more-app-multiplatform/issues/227

Show Detailed Error-Messages on Study Start

---

src/components/subComponents/IntegrationExample.vue
src/i18n/de.json
src/i18n/en.json

Extend Hints for Usage of Integration API-Keys
Closes #415

Issue #415: Extend Hints for Usage of Integration API-Keys

---

.github/workflows/test-build-push.yml

Follow-Up to #422 
References #421

Update and align upload and download actions

---

openapi/StudyManagerAPI.yaml
src/components/dialog/ChangeStudyStatusDialog.vue
src/components/forms/Overview-EditDetails.vue
src/components/forms/StudyStatusChange.vue
src/components/shared/StudyHeader.vue
src/components/study/StudyStatusPill.vue
src/i18n/de.json
src/i18n/en.json
src/stores/studyStore.ts

Frontend-Integration for the Study-Preview Mode (see MORE-Platform/more-studymanager-backend#224)
This also includes some refactoring of the Status-Dialog to a more flexible way to configure the texts for a transition.
----
Closes #437

#437: Integrate Study-Preview into StudyManager Frontend

---

src/components/StudyGroupList.vue
src/components/StudyList.vue
src/components/dialog/IntegrationDialog.vue
src/components/dialog/InterventionDialog.vue
src/components/dialog/ObservationDialog.vue
src/components/forms/Overview-EditDetails.vue
src/components/shared/MoreTable.vue

Add preview paused status to a couple of other code places, to ensure that everything what is possible in pause status is possible in preview pause status as well.

#443: Add preview paused status to missing code parts.

---

src/components/subComponents/AbsoluteSchedulerRepetition.vue

I set endDate time 1 sec before midnight, to include the last study date for observations.

#452 end of study schedule

---

src/components/ParticipantList.vue

- If the study is active or in preview, only "new" participants alias name can be changed.
- If the study in in another state except active and closed, it is possible to change alias name and study group of all participants.

#357: Differ between active and new participant as well as if the study is active or in other state.

---

.github/workflows/test-build-push.yml
openapi/StudyManagerAPI.yaml
src/components/shared/Footer.vue
src/env.d.ts
src/main.ts
vite.config.ts

There's some build error, we need to revisit this.
Reverts MORE-Platform/more-studymanager-frontend#464

Revert "#463: Show build-info in the footer"

---

.github/workflows/test-build-push.yml
openapi/StudyManagerAPI.yaml
src/components/shared/Footer.vue
src/env.d.ts
src/main.ts
vite.config.ts

* Recovered Build-Info from History after the rollback
* Fixed ENV-handling
----
Closes #463

Version & Build-Info in the Footer (2nd attempt)

---

.dockerignore
.github/workflows/test-build-push.yml
Dockerfile

Our Pipeline is a bit more complex - the final version is built within docker...
----
Closes #463

Expose Build-Id also to docker-build in the ci-pipeline

---

package-lock.json
package.json
src/components/InterventionsList.vue
src/components/ObservationList.vue
src/components/StudyGroupList.vue
src/components/TimelineList.vue
src/components/dialog/ChangeStudyStatusDialog.vue
src/components/dialog/InterventionDialog.vue
src/components/dialog/ObservationDialog.vue
src/components/dialog/StudyDialog.vue
src/components/dialog/TimelineDialog.vue
src/components/dialog/shared/StringListPropertyInput.vue
src/components/dialog/shared/StringPropertyInput.vue
src/components/dialog/shared/StringTextPropertyInput.vue
src/components/forms/InterventionTriggerConditionTable.vue
src/components/forms/InterventionTriggerConditions.vue
src/components/forms/Overview-EditDetails.vue
src/components/shared/MoreTable.vue
src/components/shared/RelativeScheduler.vue
src/components/shared/Scheduler.vue
src/components/subComponents/DatapointList.vue
src/components/subComponents/SchedulerInfoBlock.vue
src/i18n/de.json
src/i18n/en.json
src/i18n/i18n.ts
src/stores/globalStore.ts
src/stores/studyGroupStore.ts
src/views/Dashboard.vue

* Add missing translations
* Use vue i18n $d for date format
* Remove dayjs, because we use $d instead
* Use pluralization

#471: Translation clean up

---

src/components/StudyCollaboratorList.vue
src/components/dialog/shared/BooleanPropertyInput.vue
src/components/dialog/shared/IntegerPropertyInput.vue
src/components/dialog/shared/ObservationPropertyInput.vue
src/components/dialog/shared/StringPropertyInput.vue
src/components/dialog/shared/StringTextPropertyInput.vue
src/components/shared/MoreTable.vue
src/stores/studyStore.ts

* Use template literal instead of string concatenation.
* Add more specific alert message when study update request fails (from old PR-476)

#470: General clean up

---

src/components/TimelineList.vue
src/components/dialog/TimelineDialog.vue
src/models/Timeline.ts
src/types/vue-cal/index.d.ts

* Introduce TS interfaces for Timeline.
* Do not save custom data on vue-cal Event object (only cId).
* Use mapper and EventDetail object for more detailed information on e.g. dialog.
* Avoid using class names in conditions for display information.

#470: Timeline refactoring

---

src/components/shared/Header.vue
src/components/study/StudyStatusPill.vue

* Active states are green and pause states are red.
* Do not show the status color on header as border-bottom when on dashboard view.

#470: Change status color

---

src/components/ParticipationDataList.vue

* Make Seconds optional
* Make Milliseconds optional
* Timezone could be negative

#377: Improve regex to detect date-time labels

---

openapi/StudyManagerAPI.yaml
src/composable/toastService.ts
src/i18n/de.json
src/i18n/en.json

* Update StudyManagerAPI yaml to be align with BE yaml.
Related to https://github.com/MORE-Platform/more-studymanager-backend/pull/331

#434: Add detailed information (observation title) in configuration exception

---

.github/workflows/test-build-push.yml

Needed by this PR https://github.com/MORE-Platform/more-studymanager-frontend/pull/579 and the future. Align the CI workflow's Node.js version with the exact version specified in package.json for consistency. This ensures compatibility and reduces potential issues during builds.

More 578 pipeline node 18 as package

---

src/components/StudyList.vue
src/components/shared/Footer.vue
src/i18n/de.json
src/i18n/en.json
src/stores/studyStore.ts
src/utils/stringUtils.ts
src/vue-i18n.d.ts

#529 + 267: Show error when study endpoint fails + use locale to external "ABOUT MORE" link

---

package-lock.json
package.json
src/components/ParticipantList.vue

#588: Use "P xxx" as default participant name

---

package-lock.json
src/components/ParticipantList.vue
src/components/StudyList.vue
src/components/dialog/shared/BooleanPropertyInput.vue
src/components/forms/InterventionTriggerConditionTable.vue
src/components/shared/MoreTable.vue
src/components/subComponents/AbsoluteSchedulerRepetition.vue
src/styles/more-light/theme.pcss

Following issues were found while testing and fixed:
kalendar popup: header, calendar body and day numbers
absolute scheduler: repetition select buttons and information
interventions: scheduled datacheck
only once checkbox
triggerconditions layout of dropdown and buttons
some missing cursor pointers with
- table actions for file upload
- monitoring sub-tab navigation

577 fix broken UI after update deps to node 22x

---

src/components/dialog/QrCodeDialog.vue
src/components/shared/AlertMsg.vue
src/i18n/de.json
src/i18n/en.json
src/styles/more-light/theme.pcss
src/styles/print.pcss

This is the fix for the found bug from 15.5.2025: QR Code PDF preview shows duplicate pages.

More 435 fix duplicate pages for qr code pdf
